Php8 update
kodus/jpeg pull request #1
Opened 2022-08-16 11:48 UTC by JyskFynskeMedierJoej

Updated travis file
Changed tests from testies to Codeception

2022-08-16 12:07 UTC, boan-jfm approved these changes

2022-08-17 07:39 UTC, vortrixs approved these changes

2022-08-18 05:49 UTC, jrmoller commented on .gitignore
> +composer.lock
"No newline at end of file" - is it correct that composer.lock should be removed? I guess anyone using this module in a project should run an update anyway...hmmm?

2022-08-18 05:54 UTC, jrmoller commented on tests/Support/UnitTester.php
> +declare(strict_types=1);
Why declare strict here?

2022-08-18 05:55 UTC, jrmoller commented on tests/Support/UnitTester.php
> + * @SuppressWarnings(PHPMD)
Why suppress warnings?

2022-08-18 05:59 UTC, jrmoller commented on tests/Unit.suite.dist.yml
> +         - Asserts
"No newline at end of file"

2022-08-18 06:02 UTC, jrmoller commented on README.md
> +[![Build Status](https://travis-ci.org/kodus/jpeg.svg?branch=php8-update)](https://travis-ci.org/kodus/jpeg)
What does this line do?

2022-08-18 06:13 UTC, jrmoller commented on tests/Unit.suite.dist.yml
> +suite_namespace: Tests\Unit
What is the namespace used for and why is it not corresponding to the namespace in the Cest files (I checked the yml file in a random module in bitbucket - there no suite namespace was specified - that is - I don't think we usually do that)

2022-08-18 06:14 UTC, jrmoller commented on tests/Unit/CompressJPEGFileCest.php
> +namespace Kodus\JPEG\Test\Unit;
Should "Test" be "Tests"?

2022-08-18 06:18 UTC, jrmoller requested changes
Please answer the questions I have asked

2022-08-19 11:32 UTC, thomasnordahl-dk commented on README.md
> +[![Build Status](https://travis-ci.org/kodus/jpeg.svg?branch=php8-update)](https://travis-ci.org/kodus/jpeg)
These are the badges shown in the README :-)

2022-08-19 11:58 UTC, thomasnordahl-dk commented on tests/Support/UnitTester.php
> +declare(strict_types=1);
This is autogenerated by codeception. :-)

2022-08-19 11:58 UTC, thomasnordahl-dk commented on tests/Support/UnitTester.php
> + * @SuppressWarnings(PHPMD)
This is autogenerated by codeception. :-)

2022-08-19 12:00 UTC, thomasnordahl-dk commented on tests/Support/UnitTester.php
> +declare(strict_types=1);
According to the changelog they added strict types in version 5 of Codeception.

2022-08-19 12:13 UTC, thomasnordahl-dk commented on .gitignore
> +composer.lock
For some reason we've been adding lock files to our libraries and modules, but it doesn't really make sense, and I don't believe it's common practice to check these in. 

We would want our tests to be run and pass with the most recent versions of the dependencies, to ensure that our code keeps working when dependencies are updated, so locking the versions to the repository seems counterproductive.

2022-08-19 12:30 UTC, thomasnordahl-dk commented on tests/Unit.suite.dist.yml
> +suite_namespace: Tests\Unit
From the codeception changelog for version 5.0.0
> Generators create namespaced test suites by default

So before this it was sort of up to us to use namespacing with our test classes. It would probably make sense that we conform to the namespace defined by Codeception from now on. It's all under `dev` anyway, so we can sort of do what we want here :-D For existing repositories.

(It's sort of interesting that this mis-match didn't cause any errors during tests. I wonder if this config entry is even being used for anything meaningful righ now. Test classes are still loaded by scanning the directories as far as I can tell. :man_shrugging: )

2022-08-19 12:36 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGFileCest.php
> +        $I->wantTo('that the code can compress a JPEG file');
```suggestion
        $I->wantTo('compress a JPEG file');
```

2022-08-19 12:37 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGFileCest.php
> +        $I->assertTrue(file_exists($output), 'test that file exists');
```suggestion
        $I->assertTrue(file_exists($output), 'Output file was created');
```

2022-08-19 12:37 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGFileCest.php
> +        $I->assertEquals(512, $width, 'test that width is correct');
```suggestion
        $I->assertEquals(512, $width, 'width is correct');
```

2022-08-19 12:38 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGFileCest.php
> +        $I->assertEquals(512, $height, 'test that height is correct');
```suggestion
        $I->assertEquals(512, $height, height is correct');
```

2022-08-19 12:39 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGStreamCest.php
> +        $I->wantTo('that the code can compress a JPEG stream');
```suggestion
        $I->wantTo('compress a JPEG stream');
```

2022-08-19 12:40 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGStreamCest.php
> +        $I->assertEquals(512, $width, 'test that width is correct');
```suggestion
        $I->assertEquals(512, $width, 'width is correct');
```

2022-08-19 12:40 UTC, thomasnordahl-dk commented on tests/Unit/CompressJPEGStreamCest.php
> +        $I->assertEquals(512, $height, 'test that height is correct');
```suggestion
        $I->assertEquals(512, $height, 'height is correct');
```

2022-08-19 12:45 UTC, thomasnordahl-dk approved these changes
I suggested some small changes to some of the text messages that didn't seem to flow in my understanding of the code "semantics" in the test.

2022-08-22 05:55 UTC, jrmoller approved these changes
Thank you for the answers @thomasnordahl-dk

2022-08-22 07:34 UTC, vortrixs approved these changes

2022-08-22 07:37 UTC, vortrixs commented on tests/Unit/CompressJPEGFileCest.php
> +        $I->assertEquals(512, $height, height is correct');
```suggestion
        $I->assertEquals(512, $height, 'height is correct');
```

2022-08-25 08:55 UTC, merged